gems:
  - buildr >= 1.4.6

repositories:
  remote:
   - http://repo.fire.dse.vic.gov.au/content/groups/fisg
   - http://repo1.maven.org/
  release_to:
    url: http://repo.fire.dse.vic.gov.au/content/repositories/releases/
    username: upload

artifacts:
  jtds: net.sourceforge.jtds:jtds:jar:1.2.5

  #
  # JEE Libraries
  #
  javax_jms: javax.jms:jms:jar:1.1
  javax_inject: javax.inject:javax.inject:jar:1
  javax_validation: javax.validation:validation-api:jar:1.0.0.GA
  javax_validation_sources: javax.validation:validation-api:jar:sources:1.0.0.GA
  javax_ejb: org.apache.geronimo.specs:geronimo-ejb_3.1_spec:jar:1.0.2
  javax_servlet: org.apache.geronimo.specs:geronimo-servlet_3.0_spec:jar:1.0
  javax_persistence: org.hibernate.javax.persistence:hibernate-jpa-2.0-api:jar:1.0.0.Final
  javax_transaction: javax.transaction:jta:jar:1.1
  javax_annotation: com.google.code.findbugs:jsr305:jar:1.3.9
  javax_interceptor: org.jboss.spec.javax.interceptor:jboss-interceptors-api_1.1_spec:jar:1.0.0.Final
  javax_jaxrpc: org.apache.geronimo.specs:geronimo-jaxrpc_1.1_spec:jar:2.1

  #
  # JSON Jackson Libraries
  #

  jackson_core: org.codehaus.jackson:jackson-core-asl:jar:1.9.4
  jackson_mapper: org.codehaus.jackson:jackson-mapper-asl:jar:1.9.4

  #
  # GWT Libraries
  gwt_user: com.google.gwt:gwt-user:jar:2.4.0
  gwt_dev: com.google.gwt:gwt-dev:jar:2.4.0 # Due to a bug in 2.3 packaging this is required to be deployed, Fixed in 2.5
  google_guice: com.google.inject:guice:jar:3.0
  google_guice_assistedinject: com.google.inject.extensions:guice-assistedinject:jar:3.0
  aopalliance: aopalliance:aopalliance:jar:1.0 # Required for guice
  gwt_gin: com.google.gwt.inject:gin:jar:1.5.0
  gxt: com.sencha:gxt:jar:3.0.0

  #
  # Used to inject EE annotated classes in Guice
  guiceyloops: org.realityforge:guiceyloops:jar:0.3

  eclipselink: org.eclipse.persistence:eclipselink:jar:2.3.0
  #jtds: net.sourceforge.jtds:jtds:jar:1.2.4

  #
  # Mocking library used to mock out UI
  mockito: org.mockito:mockito-all:jar:1.8.5

  #
  # Used in implementation of local imitation layer
  replicant: org.realityforge:replicant:jar:0.2.36
  replicant_sources: org.realityforge:replicant:jar:sources:0.2.36
